reset snyk-security.yml

diff --git a/.github/workflows/snyk-security.yml b/.github/workflows/snyk-security.yml
--- a/.github/workflows/snyk-security.yml
+++ b/.github/workflows/snyk-security.yml
@@ -60,17 +60,17 @@ jobs:
       - name: Snyk Open Source monitor
         run: snyk monitor --all-projects
 
-      #   # Runs Snyk Infrastructure as Code (IaC) analysis and uploads result to Snyk.
-      #   # Use || true to not fail the pipeline.
-      # - name: Snyk IaC test and report
-      #   run: snyk iac test --report # || true
+        # Runs Snyk Infrastructure as Code (IaC) analysis and uploads result to Snyk.
+        # Use || true to not fail the pipeline.
+      - name: Snyk IaC test and report
+        run: snyk iac test --report # || true
 
-      #   # Build the docker image for testing
-      # - name: Build a Docker image
-      #   run: docker build -t your/image-to-test .
-      #   # Runs Snyk Container (Container and SCA) analysis and uploads result to Snyk.
-      # - name: Snyk Container monitor
-      #   run: snyk container monitor your/image-to-test --file=Dockerfile
+        # Build the docker image for testing
+      - name: Build a Docker image
+        run: docker build -t your/image-to-test .
+        # Runs Snyk Container (Container and SCA) analysis and uploads result to Snyk.
+      - name: Snyk Container monitor
+        run: snyk container monitor your/image-to-test --file=Dockerfile
 
         # Push the Snyk Code results into GitHub Code Scanning tab
       - name: Upload result to GitHub Code Scanning
